repo:
  public: okhttp-eventsource
  private: okhttp-eventsource-private

releasableBranches:
  - name: master
    description: 2.x - for Java SDK 5.0+
  - name: 1.x
    description: for Java SDK <5.0

publications:
  - url: https://oss.sonatype.org/content/groups/public/com/launchdarkly/okhttp-eventsource/
    description: Sonatype
  - url: https://javadoc.io/doc/com.launchdarkly/okhttp-eventsource
    description: documentation (javadoc.io)

template:
  name: gradle
