version: 2

repo:
  public: okhttp-eventsource
  private: okhttp-eventsource-private

jobs:
  - docker:
      image: gradle:6.8.3-jdk11
    template:
      name: gradle

branches:
  - name: main
  - name: 2.x
  - name: 1.x

publications:
  - url: https://oss.sonatype.org/content/groups/public/com/launchdarkly/okhttp-eventsource/
    description: Sonatype
  - url: https://javadoc.io/doc/com.launchdarkly/okhttp-eventsource
    description: documentation (javadoc.io)

documentation:
  gitHubPages: true

branches:
  - name: main
  - name: 2.x
  - name: 1.x
