name: Quality control checks

on:
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # false = do not cancel sibling matrix jobs when one leg fails
      matrix:
        java-version: ["8", "11", "17"]

    steps:
      - uses: actions/checkout@v4

      - name: Shared CI
        uses: ./.github/actions/ci
        with:
          java_version: ${{ matrix.java-version }}
          run_tests: true
          run_contract_tests: true

      - name: Save test results
        run: |
            mkdir -p ~/junit/;
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.java-version }} junit results
          path: ~/junit

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.java-version }} code coverage
          path: ./coverage

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    strategy:
      fail-fast: false # false = do not cancel sibling matrix jobs when one leg fails
      matrix:
        java-version: ["11.0.2.01", "17.0.1"]

    steps:
      - uses: actions/checkout@v4

      - name: install OpenJDK
        run: choco install openjdk --version ${{ matrix.java-version }}

      - run: java -version

      - name: build and test
        run: .\gradlew.bat --no-daemon test

      - name: save test results
        run: |
            mkdir .\junit
            cp build/test-results/test/*.xml junit

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.java-version }} junit results
          path: .\junit
